export const DATA = [
  {
    TransactionId: 1,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Dale Cotton",
    Amount: "$28.43",
  },
  {
    TransactionId: 2,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Paul Carter",
    Amount: "$45.16",
  },
  {
    TransactionId: 3,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Caldwell Reid",
    Amount: "$63.00",
  },
  {
    TransactionId: 4,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Quentin Bonner",
    Amount: "$64.52",
  },
  {
    TransactionId: 5,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Colt Joyce",
    Amount: "$70.67",
  },
  {
    TransactionId: 6,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Neil Walls",
    Amount: "$99.36",
  },
  {
    TransactionId: 7,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Slade Rios",
    Amount: "$52.60",
  },
  {
    TransactionId: 8,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Graham Harrell",
    Amount: "$47.51",
  },
  {
    TransactionId: 9,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Kirk Byers",
    Amount: "$96.35",
  },
  {
    TransactionId: 10,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Holmes Howell",
    Amount: "$93.81",
  },
  {
    TransactionId: 11,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Flynn Whitley",
    Amount: "$95.75",
  },
  {
    TransactionId: 12,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Chase Salas",
    Amount: "$95.25",
  },
  {
    TransactionId: 13,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Aquila Skinner",
    Amount: "$69.47",
  },
  {
    TransactionId: 14,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Len Snyder",
    Amount: "$78.59",
  },
  {
    TransactionId: 15,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Thaddeus Watts",
    Amount: "$38.72",
  },
  {
    TransactionId: 16,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Nehru Franks",
    Amount: "$51.22",
  },
  {
    TransactionId: 17,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Lester Oconnor",
    Amount: "$13.45",
  },
  {
    TransactionId: 18,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Jameson White",
    Amount: "$38.76",
  },
  {
    TransactionId: 19,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Christian Stanton",
    Amount: "$91.79",
  },
  {
    TransactionId: 20,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Vance Lowery",
    Amount: "$13.40",
  },
  {
    TransactionId: 21,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Kevin Wiley",
    Amount: "$42.04",
  },
  {
    TransactionId: 22,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Plato Clay",
    Amount: "$51.64",
  },
  {
    TransactionId: 23,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Salvador Hardy",
    Amount: "$60.54",
  },
  {
    TransactionId: 24,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Owen Langley",
    Amount: "$64.23",
  },
  {
    TransactionId: 25,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Zeus Ferrell",
    Amount: "$32.59",
  },
  {
    TransactionId: 26,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Hayden Puckett",
    Amount: "$14.49",
  },
  {
    TransactionId: 27,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Raja Fitzpatrick",
    Amount: "$56.88",
  },
  {
    TransactionId: 28,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Hedley Mccall",
    Amount: "$33.87",
  },
  {
    TransactionId: 29,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Ivan Noble",
    Amount: "$55.21",
  },
  {
    TransactionId: 30,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Steven Soto",
    Amount: "$94.57",
  },
  {
    TransactionId: 31,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Omar Hutchinson",
    Amount: "$54.11",
  },
  {
    TransactionId: 32,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Thor Mack",
    Amount: "$7.84",
  },
  {
    TransactionId: 33,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Charles Sullivan",
    Amount: "$76.74",
  },
  {
    TransactionId: 34,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Thor Gilbert",
    Amount: "$90.68",
  },
  {
    TransactionId: 35,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Gabriel Fox",
    Amount: "$54.20",
  },
  {
    TransactionId: 36,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Driscoll Tate",
    Amount: "$72.10",
  },
  {
    TransactionId: 37,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Armando Chase",
    Amount: "$99.65",
  },
  {
    TransactionId: 38,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Thane Donovan",
    Amount: "$84.18",
  },
  {
    TransactionId: 39,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Price Dudley",
    Amount: "$15.81",
  },
  {
    TransactionId: 40,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Yuli Brown",
    Amount: "$67.19",
  },
  {
    TransactionId: 41,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Jin Prince",
    Amount: "$95.10",
  },
  {
    TransactionId: 42,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Beck Butler",
    Amount: "$64.97",
  },
  {
    TransactionId: 43,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Victor Quinn",
    Amount: "$16.88",
  },
  {
    TransactionId: 44,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Dane Barker",
    Amount: "$25.31",
  },
  {
    TransactionId: 45,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Felix Harper",
    Amount: "$82.36",
  },
  {
    TransactionId: 46,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Merrill Mullen",
    Amount: "$30.56",
  },
  {
    TransactionId: 47,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Laith Villarreal",
    Amount: "$74.68",
  },
  {
    TransactionId: 48,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Abraham Justice",
    Amount: "$63.24",
  },
  {
    TransactionId: 49,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Nathan Whitfield",
    Amount: "$59.82",
  },
  {
    TransactionId: 50,
    Status: "Completed",
    Type: "Refill",
    ClientName: "David Rice",
    Amount: "$84.71",
  },
  {
    TransactionId: 51,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Reuben Webb",
    Amount: "$87.83",
  },
  {
    TransactionId: 52,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Lawrence Duffy",
    Amount: "$10.96",
  },
  {
    TransactionId: 53,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Hakeem Acevedo",
    Amount: "$40.66",
  },
  {
    TransactionId: 54,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Daquan Shields",
    Amount: "$16.36",
  },
  {
    TransactionId: 55,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Adam Shepherd",
    Amount: "$45.97",
  },
  {
    TransactionId: 56,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Derek Todd",
    Amount: "$52.88",
  },
  {
    TransactionId: 57,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Nigel Roach",
    Amount: "$46.92",
  },
  {
    TransactionId: 58,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Oleg Willis",
    Amount: "$97.76",
  },
  {
    TransactionId: 59,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Chancellor Stewart",
    Amount: "$70.30",
  },
  {
    TransactionId: 60,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Gray Barry",
    Amount: "$85.78",
  },
  {
    TransactionId: 61,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Cairo Mack",
    Amount: "$73.98",
  },
  {
    TransactionId: 62,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Erasmus Oneal",
    Amount: "$89.31",
  },
  {
    TransactionId: 63,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Levi Shepherd",
    Amount: "$64.08",
  },
  {
    TransactionId: 64,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Cody York",
    Amount: "$70.00",
  },
  {
    TransactionId: 65,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Armand Miller",
    Amount: "$10.93",
  },
  {
    TransactionId: 66,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Jameson Warren",
    Amount: "$90.01",
  },
  {
    TransactionId: 67,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Merritt Nieves",
    Amount: "$19.69",
  },
  {
    TransactionId: 68,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Callum Rosa",
    Amount: "$43.04",
  },
  {
    TransactionId: 69,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "James Garcia",
    Amount: "$92.82",
  },
  {
    TransactionId: 70,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Kasimir Sandoval",
    Amount: "$37.16",
  },
  {
    TransactionId: 71,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Noble Frank",
    Amount: "$94.88",
  },
  {
    TransactionId: 72,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Cade Emerson",
    Amount: "$47.94",
  },
  {
    TransactionId: 73,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Sean Head",
    Amount: "$11.36",
  },
  {
    TransactionId: 74,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Ross Crawford",
    Amount: "$24.13",
  },
  {
    TransactionId: 75,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Salvador Hopkins",
    Amount: "$47.86",
  },
  {
    TransactionId: 76,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Quamar Peck",
    Amount: "$5.46",
  },
  {
    TransactionId: 77,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Norman Whitley",
    Amount: "$35.88",
  },
  {
    TransactionId: 78,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Dexter Chandler",
    Amount: "$34.61",
  },
  {
    TransactionId: 79,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Adam Curry",
    Amount: "$69.92",
  },
  {
    TransactionId: 80,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Elmo Huffman",
    Amount: "$15.07",
  },
  {
    TransactionId: 81,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Eaton Sanchez",
    Amount: "$31.20",
  },
  {
    TransactionId: 82,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Cooper Cantrell",
    Amount: "$14.69",
  },
  {
    TransactionId: 83,
    Status: "Cancelled",
    Type: "Withdrawal",
    ClientName: "Kermit Lawrence",
    Amount: "$86.51",
  },
  {
    TransactionId: 84,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Arsenio Wilkinson",
    Amount: "$76.06",
  },
  {
    TransactionId: 85,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Francis Marks",
    Amount: "$93.64",
  },
  {
    TransactionId: 86,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Robert Nunez",
    Amount: "$62.78",
  },
  {
    TransactionId: 87,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Hyatt Spence",
    Amount: "$74.23",
  },
  {
    TransactionId: 88,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Elmo Oliver",
    Amount: "$0.73",
  },
  {
    TransactionId: 89,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Brent Skinner",
    Amount: "$48.10",
  },
  {
    TransactionId: 90,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Linus Garcia",
    Amount: "$61.99",
  },
  {
    TransactionId: 91,
    Status: "Pending",
    Type: "Refill",
    ClientName: "Bruce Vaughn",
    Amount: "$16.55",
  },
  {
    TransactionId: 92,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Galvin Knapp",
    Amount: "$90.98",
  },
  {
    TransactionId: 93,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Timothy Martinez",
    Amount: "$36.48",
  },
  {
    TransactionId: 94,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Myles Wright",
    Amount: "$87.57",
  },
  {
    TransactionId: 95,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Robert Beard",
    Amount: "$35.86",
  },
  {
    TransactionId: 96,
    Status: "Completed",
    Type: "Refill",
    ClientName: "Brendan Santana",
    Amount: "$38.22",
  },
  {
    TransactionId: 97,
    Status: "Cancelled",
    Type: "Refill",
    ClientName: "Quamar Avery",
    Amount: "$34.22",
  },
  {
    TransactionId: 98,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Upton Perez",
    Amount: "$32.31",
  },
  {
    TransactionId: 99,
    Status: "Completed",
    Type: "Withdrawal",
    ClientName: "Grady Gordon",
    Amount: "$7.33",
  },
  {
    TransactionId: 100,
    Status: "Pending",
    Type: "Withdrawal",
    ClientName: "Mark Velazquez",
    Amount: "$66.59",
  },
];
